socialauth/eventos/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'socialauth.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^listado/$', login_required(views.EventosView.as_view()), name='listado'),
    url(r'^evento/(?P<pk>\d+)/$', login_required(views.DetallesView.as_view()), name='evento'),
    url(r'^evento/(?P<pk>\d+)/registrar$', views.registrar, name='registrar'),
)

socialauth/socialauth/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'socialauth.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^eventos/', include('eventos.urls', namespace='eventos')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

socialauth/eventos/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.template import defaultfilters as df

class Evento(models.Model):
    nombre = models.CharField(max_length=50)
    asistentes = models.ManyToManyField(User, through='Asistente_Evento')
    lugar = models.CharField(max_length=50)
    fecha = models.DateTimeField()
    duracion_horas = models.IntegerField('horas aproximadas de duración')
    max_asistentes = models.IntegerField('número máximo de asistentes')
    
    def __unicode__(self):
        return unicode(self.nombre) + ' | ' + df.date(self.fecha, "F d, Y")

class Asistente_Evento(models.Model):
    evento = models.ForeignKey(Evento)
    asistente = models.ForeignKey(User)
    
    class Meta:
        unique_together = ('evento', 'asistente')
        verbose_name = 'asistente'
        
    def __unicode__(self):
        return unicode(self.evento) + ' | ' + unicode(self.asistente)

socialauth/eventos/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from models import Evento, Asistente_Evento
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.template import defaultfilters as df
import facebook


class HomeView(generic.TemplateView):
    template_name = "eventos/home.html"

class EventosView(generic.ListView):
    template_name = 'eventos/eventos.html'
    context_object_name = 'eventos'

    def get_queryset(self):
        return Evento.objects.order_by('-fecha')

class DetallesView(generic.DetailView):
    model = Evento
    template_name = 'eventos/evento.html'
    
    def get_context_data(self, **kwargs):
        context = super(DetallesView, self).get_context_data(**kwargs)
        context['disponible'] = True
        if self.get_object().asistentes.filter(
            pk=self.request.user.pk) or self.get_object().fecha < timezone.now():
            context['disponible'] = False
        return context

@login_required
def registrar(request, pk):
    evento = get_object_or_404(Evento, pk=pk)
    mensaje = "Voy a asistir al evento " + evento.nombre + " cuya fecha es: " + df.date(evento.fecha, "F d, Y")
    user = request.user
    social_user = user.social_auth.first()
    asistente_evento = Asistente_Evento(asistente=user, evento=evento)
    try:
        asistente_evento.save()
        graph = facebook.GraphAPI(social_user.extra_data['access_token'])
        graph.put_object('me', 'feed', message=mensaje, link="http://www.test1.com",
            picture='http://www.thefamilyfocus.ca/images/Inserts/Calendar.png')
    except:
        messages.add_message(request, messages.ERROR, "Se ha producido un error!")
    else:
        messages.add_message(request, messages.INFO,
            "Gracias por registrar tu asistencia. Esta accion ha sido publicada en tu muro de fb.")
        return HttpResponseRedirect(reverse('eventos:evento', args=[evento.pk]))

socialauth/eventos/templates/eventos/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Python Social Auth - Demo{% endblock %}</title>
	<link href="{% static 'eventos/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'eventos/css/bootstrap-theme.min.css' %}" rel="stylesheet">
	<link href="{% static 'eventos/css/main.css' %}" rel="stylesheet">
</head>
<body>
	<div id="body" class="container">
		<div class="col-md-12">
			<div class="navbar navbar-inverse" role="navigation" id="nav">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span> 
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
							<li><a href="{% url 'eventos:home' %}">Home</a></li> 
							{% if user.is_authenticated and not user.is_superuser %}
							<li><a href="{% url 'eventos:listado' %}">Eventos</a></li>
							<li><a href="{% url 'auth:logout' %}?next={% url 'eventos:home' %}">Logout</a></li>
							{% endif %}
						</ul>
					</div>
					<!--/.nav-collapse -->
				</div>
				<!--/.container-fluid -->
			</div>
		</div>
		<div class="content wrapperContenido col-md-12">
			<div class="contenido bordesContenedores fondoContenedores">
			    {% if messages %}
                    {% for message in messages %}
                        {% if forloop.last %}<p><i>{{ message }}</i></p>{% endif %}
                    {% endfor %}
                {% endif %}
			    <h4>{% block content_title %}{% endblock %}</h4>
			    <hr>
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="{% static 'thirdauth/js/bootstrap.min.js' %}"></script>
</body>
</html>

socialauth/eventos/templates/eventos/evento.html
{% extends 'eventos/base.html' %}

{% block content_title %}{{ evento.nombre }}{% endblock %}

{% block content %}

<ul>
    <li>Lugar: {{ evento.lugar }}</li>
    <li>Fecha: {{ evento.fecha }}</li>
    <li>Número máximo de asistencia: {{ evento.max_asistentes }}</li>
    <li>Horas aproximadas de duracion: {{ evento.duracion_horas }}</li>
    <li>Asistentes:
        <ul>
        {% for asistente in evento.asistentes.all %}
            <li>{{ asistente.first_name }} {{ asistente.last_name }}</li>
        {% endfor %}
        </ul>
    </li>
    <br>
    {% if disponible %}
        <a href="{% url 'eventos:registrar' evento.pk %}" class="btn btn-primary">
            Registrar Asistencia
        </a>       
    {% endif %}
</ul>



{% endblock %}

socialauth/eventos/templates/eventos/eventos.html
{% extends 'eventos/base.html' %}

{% block content_title %}Eventos Disponibles{% endblock %}

{% block content %}

{% if eventos %}
    <ul>
    {% for evento in eventos %}
        <li><a href="{% url 'eventos:evento' evento.pk %}">{{ evento }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No existen eventos almacenados.</p>
{% endif %}

{% endblock %}

socialauth/eventos/templates/eventos/home.html
{% extends 'eventos/base.html' %}

{% block content %}

{% if user.is_authenticated and not user.is_superuser %}
    <h3>Bienvenid@ {{ user.first_name }}!</h3> 
{% else %}
    <a href="{% url 'social:begin' 'facebook' %}?next={% url 'eventos:home' %}" class="btn btn-primary">
        Identificarse con Facebook
    </a>
{% endif %}

{% endblock %}